version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3124:3000"
    volumes:
      - .:/usr/ltphat/src/webproj
      - /usr/ltphat/src/webproj
    depends_on:
      - postgres
    container_name: online-news-app
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
    container_name: online-news-nginx-server
    restart: always

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: online-news
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    container_name: local-postgres
    restart: always

volumes:
  postgres_data: